### ISSUE TITLE
forge crash when right clicking on explorer's  compass

### ISSUE THREAD

**Issue by DragonEater2008** [MattCzyr/ExplorersCompass#20]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 3/14/22, 7:11 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.world.level.levelgen.StructureSettings net.minecraft.world.level.chunk.ChunkGenerator.m_62205_()'
	at com.chaosthedude.explorerscompass.util.StructureUtils.getStructureDimensions(StructureUtils.java:115) ~[ExplorersCompass-1.18.1-1.1.2-forge.jar%2369!/:1.18.1-1.1.2-forge] {re:classloading}
	at com.chaosthedude.explorerscompass.util.StructureUtils.getDimensionsForAllowedStructures(StructureUtils.java:136) ~[ExplorersCompass-1.18.1-1.1.2-forge.jar%2369!/:1.18.1-1.1.2-forge] {re:classloading}
	at com.chaosthedude.explorerscompass.items.ExplorersCompassItem.m_7203_(ExplorersCompassItem.java:50) ~[ExplorersCompass-1.18.1-1.1.2-forge.jar%2369!/:1.18.1-1.1.2-forge] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:252) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:293) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1017) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:25) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220228.144236-srg.jar%2391!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1167998072 bytes (1113 MiB) / 11475615744 bytes (10944 MiB) up to 15032385536 bytes (14336 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GT 730
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1287
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5671
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23758.77
	Virtual memory used (MB): 21079.74
	Swap memory total (MB): 7424.00
	Swap memory used (MB): 602.46
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx14G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['DragonEater20'/38814, l='ServerLevel[gears]', x=884.14, y=62.07, z=238.00]]
	Data Packs: vanilla, mod:amplifiednether, mod:notenoughcrashes (incompatible), mod:enchdesc (incompatible), mod:terrablender (incompatible), mod:trashslot (incompatible), mod:biomesoplenty (incompatible), mod:firstpersonmod (incompatible), mod:jei (incompatible), mod:configurabledespawntimer, mod:kleeslabs (incompatible), mod:notenoughanimations (incompatible), mod:patchouli (incompatible), mod:xaerominimap, mod:collective, mod:xaeroworldmap, mod:shutupexperimentalsettings (incompatible), mod:controlling (incompatible), mod:naturescompass (incompatible), mod:configured (incompatible), mod:colouredtooltips (incompatible), mod:snowundertrees (incompatible), mod:eatinganimation (incompatible), mod:deleteworldstotrash (incompatible), mod:simpleplanes (incompatible), mod:explorerscompass (incompatible), mod:ferritecore (incompatible), mod:connectedglass (incompatible), mod:clickadv (incompatible), mod:rangedwirelessredstone (incompatible), mod:catalogue (incompatible), mod:balm (incompatible), mod:terralith, mod:cloth_config (incompatible), mod:forge (incompatible), mod:appleskin (incompatible), mod:voidtotem (incompatible), mod:konkrete (incompatible), mod:bettermodsbutton (incompatible), mod:ironchest (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 1
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.2-20220228.144236-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Amplified_Nether_v1.1.1.jar                       |Amplified Nether              |amplifiednether               |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		notenoughcrashes-4.1.4+1.18.1-forge.jar           |Not Enough Crashes            |notenoughcrashes              |4.1.4+1.18.1        |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.18.1-9.0.11.jar   |EnchantmentDescriptions       |enchdesc                      |9.0.11              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.18.2-1.1.0.91.jar            |TerraBlender                  |terrablender                  |1.18.2-1.1.0.91     |DONE      |Manifest: NOSIGNATURE
		trashslot-forge-1.18.1-11.0.2.jar                 |TrashSlot                     |trashslot                     |11.0.2              |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.2-16.0.0.107-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.2-16.0.0.107   |DONE      |Manifest: NOSIGNATURE
		firstperson-forge-2.1.0-mc1.18.jar                |FirstPersonModel Mod          |firstpersonmod                |2.1.0-mc1.18        |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.5.0.132.jar                          |Just Enough Items             |jei                           |9.5.0.132           |DONE      |Manifest: NOSIGNATURE
		configurabledespawntimer_1.18.2-2.5.jar           |Configurable Despawn Timer    |configurabledespawntimer      |2.5                 |DONE      |Manifest: NOSIGNATURE
		kleeslabs-forge-1.18.1-11.1.0.jar                 |KleeSlabs                     |kleeslabs                     |11.1.0              |DONE      |Manifest: NOSIGNATURE
		notenoughanimations-forge-1.4.0-mc1.18.jar        |NotEnoughAnimations Mod       |notenoughanimations           |1.4.0               |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-66.jar                           |Patchouli                     |patchouli                     |1.18.2-66           |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.3.1_Forge_1.18.2.jar            |Xaero's Minimap               |xaerominimap                  |22.3.1              |DONE      |Manifest: NOSIGNATURE
		collective-1.18.2-4.24.jar                        |Collective                    |collective                    |4.24                |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.20.4_Forge_1.18.2.jar            |Xaero's World Map             |xaeroworldmap                 |1.20.4              |DONE      |Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.4-1.18+.jar        |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.4               |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.18.2-9.0+17.jar               |Controlling                   |controlling                   |9.0+17              |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.18.2-1.9.5-forge.jar             |Nature's Compass              |naturescompass                |1.18.2-1.9.5-forge  |DONE      |Manifest: NOSIGNATURE
		configured-1.5.3-1.18.1.jar                       |Configured                    |configured                    |1.5.3               |DONE      |Manifest: NOSIGNATURE
		ColouredTooltips-Forge-1.18.2-15.0.1.jar          |ColouredTooltips              |colouredtooltips              |15.0.1              |DONE      |Manifest: NOSIGNATURE
		snowundertrees-1.18.2-1.2.jar                     |Snow Under Trees              |snowundertrees                |1.2                 |DONE      |Manifest: NOSIGNATURE
		eatinganimation-1.18.1-2.0.1.jar                  |Eating Animation              |eatinganimation               |2.0.0               |DONE      |Manifest: NOSIGNATURE
		DeleteWorldsToTrash-v3.2.0-1.18.2-Forge.jar       |Delete Worlds To Trash        |deleteworldstotrash           |3.2.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		simpleplanes-1.18.2-4.11.1.jar                    |Simple Planes                 |simpleplanes                  |1.18.2-4.11.1       |DONE      |Manifest: NOSIGNATURE
		ExplorersCompass-1.18.1-1.1.2-forge.jar           |Explorer's Compass            |explorerscompass              |1.18.1-1.1.2-forge  |DONE      |Manifest: NOSIGNATURE
		ferritecore-4.2.0-forge.jar                       |Ferrite Core                  |ferritecore                   |4.2.0               |DONE      |Manifest: NOSIGNATURE
		connectedglass-1.1.1-mc1.18.jar                   |Connected Glass               |connectedglass                |1.1.1               |DONE      |Manifest: NOSIGNATURE
		clickadvancements-1.18-2.0.jar                    |clickadv mod                  |clickadv                      |1.18-2.0            |DONE      |Manifest: NOSIGNATURE
		rangedwirelessredstone-1.18-2.0.1.jar             |Ranged Wireless Redstone      |rangedwirelessredstone        |1.18-2.0.1          |DONE      |Manifest: NOSIGNATURE
		catalogue-1.6.0-1.18.1.jar                        |Catalogue                     |catalogue                     |1.6.0               |DONE      |Manifest: NOSIGNATURE
		balm-3.0.1+0.jar                                  |Balm                          |balm                          |3.0.1+0             |DONE      |Manifest: NOSIGNATURE
		Terralith_v2.2.jar                                |Terralith                     |terralith                     |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.2.57-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.2.57              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.0.13-universal.jar                |Forge                         |forge                         |40.0.13             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.18-2.3.0.jar                  |AppleSkin                     |appleskin                     |2.3.0+mc1.18        |DONE      |Manifest: NOSIGNATURE
		voidtotem-forge-1.18.2-1.3.0.jar                  |Void Totem                    |voidtotem                     |1.18.2-1.3.0        |DONE      |Manifest: NOSIGNATURE
		konkrete_forge_1.3.3_MC_1.18-1.18.1.jar           |Konkrete                      |konkrete                      |1.3.3               |DONE      |Manifest: NOSIGNATURE
		BetterModsButton-v3.2.0-1.18.2-Forge.jar          |Better Mods Button            |bettermodsbutton              |3.2.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		ironchest-1.18-13.0.7.jar                         |Iron Chests                   |ironchest                     |1.18-13.0.7         |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 79081cdf-0bd9-48c8-95a7-c700b59b641a
	FML: 40.0
	Forge: net.minecraftforge:40.0.13
	Suspected Mods: Explorer's Compass (explorerscompass), Minecraft (minecraft)

**Comment by MattCzyr** [comment]
The version of Explorer's Compass that you're using is only compatible with 1.18.1, not 1.18.2. A version for 1.18.2 will be released soon. Will post here when it is out.

**Comment by MattCzyr** [comment]
Version 1.18.2-1.2.0-forge is now released.
